### ISSUE TITLE
batch eth_call response JSONDecodeError

### ISSUE THREAD

**Issue by will0x0909** [erpc/erpc#101]
parameters
[{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x7786729eee8b9d30fe7d91fdff23a0f1d0c615d9","data":"0x18160ddd"},"latest"],"id":0},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xfae103dc9cf190ed75350761e95403b7b8afa6c0","data":"0x18160ddd"},"latest"],"id":1},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x3bdca51226202fc2a64211aa35a8d95d61c6ca99","data":"0x18160ddd"},"latest"],"id":2},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x41e4a828630dd4729fc010e9483cd900bb37fc79","data":"0x18160ddd"},"latest"],"id":3},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x56e6f1bffde5dccd9a183585ce31f2902fc52707","data":"0x18160ddd"},"latest"],"id":4},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x75cd3f538c091c1d514ab1ad9832f54198cacec0","data":"0x18160ddd"},"latest"],"id":5},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xd96f0bcfd476bcd32935c010bd638a3fc25042eb","data":"0x18160ddd"},"latest"],"id":6},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x5e7a28a4156d10b83701b31db1746484f377fb67","data":"0x18160ddd"},"latest"],"id":7},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0x2260fac5e5542a773aa44fbcfedf7c193bc2c599","data":"0x18160ddd"},"latest"],"id":8},{"jsonrpc":"2.0","method":"eth_call","params":[{"to":"0xd31a59c85ae9d8edefec411d448f90841571b89c","data":"0x18160ddd"},"latest"],"id":9}]

got response 
[,{"jsonrpc":"2.0","id":1,"result":"0x000000000000000000000000000000000000000000000f2acc45cda1eb4d9a9a"},{"jsonrpc":"2.0","id":2,"result":"0x0000000000000000000000000000000000000000000000000000000000008859"},{"jsonrpc":"2.0","id":3,"result":"0x0000000000000000000000000000000000000000000000000000000000000000"},{"jsonrpc":"2.0","id":4,"result":"0x0000000000000000000000000000000000000000000000000000000000000000"},{"jsonrpc":"2.0","id":5,"result":"0x000000000000000000000000000000000000000000000000000000000000108c"},{"jsonrpc":"2.0","id":6,"result":"0x00000000000000000000000000000000000000000000000000000001d85f1290"},{"jsonrpc":"2.0","id":7,"result":"0x00000000000000000000000000000000000000000000000000a6fa4040718000"},{"jsonrpc":"2.0","id":8,"result":"0x00000000000000000000000000000000000000000000000000000d586d5572ab"},{"jsonrpc":"2.0","id":9,"result":"0x00000000000000000000000000000000000000000000000000017906e43ed284"}]

as you can see, the first element is missed。This happened frequently when using python multiprocess to send the requests, can you tell me how to avoid this. And here is my erpc.yaml file

logLevel: warn
database:
  evmJsonRpcCache:
    # driver: memory
    driver: postgresql
    postgresql:
      connectionUri: >-
        ***postgres***
      table: rpc_cache
server:
  httpHostV4: 0.0.0.0
  httpPort: 4000
  maxTimeout: 50s
metrics:
  enabled: true
  hostV4: 0.0.0.0
  port: 4001
projects:
  - id: main
    networks:
      - architecture: evm
        evm:
          chainId: 1
        failsafe:
          timeout:
            duration: 30s
          retry:
            maxCount: 3
            delay: 500ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
          hedge:
            delay: 3000ms
            maxCount: 2
    upstreams:
      - id: blastapi-chain-1
        type: evm
        endpoint: ***blast-rpc***
        rateLimitBudget: global-blast
        evm:
          chainId: 1
        failsafe:
          timeout:
            duration: 15s
          retry:
            maxCount: 2
            delay: 1000ms
            backoffMaxDelay: 10s
            backoffFactor: 0.3
            jitter: 500ms
rateLimiters:
  budgets:
    - id: default-budget
      rules:
        - method: '*'
          maxCount: 100000
          period: 1s
    - id: global-blast
      rules:
        - method: '*'
          maxCount: 100000
          period: 1s
    - id: global-quicknode
      rules:
        - method: '*'
          maxCount: 300000
          period: 1s

**Comment by aramalipoor** [comment]
Thanks @will0x0909 for reporting looking into it

**Comment by will0x0909** [comment]
> Thanks @will0x0909 for reporting looking into it. Which image version are you using?

I clone main branch, and execute `make run` manually

**Comment by will0x0909** [comment]
> Did few tests couldn't reproduce this. Do you see any warn/error in your logs?
> 
> I have added a new commit to print an error when a batch item is empty, maybe if you can try with the new main. I'll try to reproduce with few other configs in meantime...

Thanks a lot, I will try it later

**Comment by will0x0909** [comment]
Seemed wouldn't happen again now。thanks again

**Comment by kasrakhosravi** [comment]
@will0x0909 please let us know if any other issues come up in your testing :)
