### ISSUE TITLE
feature: add default config options in the documentation

### ISSUE THREAD

**Issue by Zygimantass** [erpc/erpc#127]
**Is your feature request related to a problem? Please describe.**

I was surprised that metrics were not enabled by default

**Describe the solution you'd like**

Document the monitoring config options in the monitoring section and also add a section for the default configuration options (if you do not provide any).

**Describe alternatives you've considered**
Enable metrics by default

**Comment by aramalipoor** [comment]
Good idea @Zygimantass to explicitly mention the defaults.

Metrics also must be enabled by default if it's not probably a regression after updating config validations. Will investigate and update in next release.

**Comment by aramalipoor** [comment]
Fixed in https://github.com/erpc/erpc/commit/b91556e8657c6d4288971a76c6a5a30139a06944 will be in next release.
