### ISSUE TITLE
bug: TS rate limit budget config object causes Go panic

### ISSUE THREAD

**Issue by andrewwahid** [erpc/erpc#134]
**Describe the bug**
Adding a RateLimitBudgetConfig to rateLimiters causes Go to panic/crash because of type conversions

**To Reproduce**
1. Use this erpc.ts config:
```ts
import {createConfig} from "@erpc-cloud/config";
export default createConfig({
  logLevel: "debug",
  database: {
    evmJsonRpcCache: undefined
  },
  server: {
    listenV4: true,
    httpHostV4: "0.0.0.0",
  },
  projects: [
    {
      id: "main",
      upstreams: [
        {
          id: "ethereum",
          type: "evm",
          rateLimitBudget: "public-node-budget",
          endpoint: "https://ethereum-rpc.publicnode.com"
        }
      ]
    },
  ],
  rateLimiters: {
    budgets: [
      {
        id: "public-node-budget",
        rules: [
          {
            method: "*",
            maxCount: 20,
            period: "1s",
            waitTime: "2s"
          }
        ]
      }
    ]
  },
});
```
2. Run ERPC:
```bash
docker run -v $(pwd)/erpc.ts:/root/erpc.ts -p 4000:4000 -p 4001:4001 ghcr.io/erpc/erpc:latest
```

You should see this error: `panic: reflect: call of reflect.Value.SetInt on uint Value`
I think this error has to do with parsing budget.rules[i].maxCount

**Expected behavior**
ERPC to parse TS config correctly and run without errors/crashes

**Comment by aramalipoor** [comment]
@andrewwahid this is actually already solved in https://github.com/erpc/erpc/releases/tag/0.0.34 

It was fixed as part of this PR https://github.com/erpc/erpc/pull/123

Let me know how it goes with this version (btw the breaking changes are easy to update ;)

**Comment by andrewwahid** [comment]
@aramalipoor I thought I was on the latest version, thanks for the help, I can confirm it now works under 0.0.34
