### ISSUE TITLE
Block finality checking on cache retrieval

### ISSUE THREAD

**Issue by xJonathanLEI** [erpc/erpc#45]
## Context

For context, I'm trying to use `erpc` as a completely offline test fixture. This could be for running integration tests for CI, or just working in an environment where node access is slow / not possible. I understand this might not be a supported use case for `erpc` but given its capability of using a persistent cache it's a great fit.

## The issue

The issue I have so far, after fixing the obvious bugs in #41 and #42 where cache misses unexpectedly happen, is that the cache retrieval code checks for block finality:

https://github.com/erpc/erpc/blob/9371a74379a8fc0243664cf7caff6605982dd8ac/erpc/evm_json_rpc_cache.go#L66-L74

This is problematic because:

1. when running offline or when all upstreams are down when you start, you wouldn't even be able to serve from cache;
2. the very first requests served after `erpc` starts up _always miss the cache_ as the block tracker hasn't fetched the finalized block yet.

While issue 1 might not be what `erpc` cares about since it's a proxy at the end of the day, issue 2 _does_ cause slight performance degradation when scaling / rolling updates. So it might be worth fixing after all.

But why do we even check for finality here? I can see why we want to do it when setting cache, but is it really necessary to do it when fetching? If it weren't finalized in the first place it wouldn't have been in the cache.

One counter argument I can see here is that checking for finality helps avoids unnecessary IO to the cache store. If the block is too recent, no checking with storage is needed, so better latency. But I have a proposed solution:

## Proposed solution

So right now `EvmIsBlockFinalized()` returns `false` when the finalized block is not yet available:

https://github.com/erpc/erpc/blob/9371a74379a8fc0243664cf7caff6605982dd8ac/erpc/networks.go#L308-L315

I think this is rather inaccurate. How do you know the block is not finalized if you don't know the finalized block? This should rather be an error. If we turn this into an error, the cache fetching code can then distinguish between "definitely not finalized" and "we don't know.. maybe?". And in the case of "we don't know", we can still hit storage to find out whether we actually have it.

This should have no impact on any other parts as I've checked and so far all other callsites treat error and `false` the same.

**Comment by xJonathanLEI** [comment]
@aramalipoor Not sure if this is what you'd want but optimistically submitted #46.

**Comment by aramalipoor** [comment]
@xJonathanLEI This is a great summary, and also a good answer to this question that I had few days ago:
What to do when finalized block is not yet known?

"An error to distinguish 'unknown' -> assume 'finalized' during get and 'unfinalized' during set"

---

Re 'why should we even do this?' as you said it's to avoid redundant reads when can be avoided cheaply for real-time use-cases (frontend clients, indexers live ingestion, etc), which will send lots of these.
