### ISSUE TITLE
Unable to pull `erpc` images

### ISSUE THREAD

**Issue by leovct** [erpc/erpc#75]
## Description

Unable to pull `erpc` images. I think it may be related to this commit: https://github.com/erpc/erpc/commit/ab19be7ea5816af301ac33d24c1b5157e5b2e279.

```bash
$ docker run --rm -it ghcr.io/erpc/erpc:0.0.24 /bin/bash
Unable to find image 'ghcr.io/erpc/erpc:0.0.24' locally
0.0.24: Pulling from erpc/erpc
docker: manifest unknown.
See 'docker run --help'.
```

```bash
$ docker run --rm -it ghcr.io/erpc/erpc:latest /bin/bash
Unable to find image 'ghcr.io/erpc/erpc:latest' locally
latest: Pulling from erpc/erpc
docker: manifest unknown.
See 'docker run --help'.
```

It also happens for older images.

```bash
$ docker run --rm -it ghcr.io/erpc/erpc:0.0.23 /bin/bash
Unable to find image 'ghcr.io/erpc/erpc:0.0.23' locally
0.0.23: Pulling from erpc/erpc
docker: manifest unknown.
See 'docker run --help'.
```

**Comment by aramalipoor** [comment]
@leovct looking into it now 🤦🏻‍♂️

**Comment by aramalipoor** [comment]
@leovct rebuilt the 0.0.24 and latest, will mark this GHA as dry-run for now. Thanks for reporting.

Let me know if you want other tags, need to think how automatically I can bring them back quickly.

**Comment by leovct** [comment]
Last version works fine for me!

It was previously [failing](https://github.com/0xPolygon/kurtosis-cdk/actions/runs/11436776463/job/31815831702?pr=312), now it's [working](https://github.com/0xPolygon/kurtosis-cdk/actions/runs/11436776463/job/31818037733) again. Thanks for the quick fix!
