### ISSUE TITLE
Bug: occasionally empty eth_protocolVersion response

### ISSUE THREAD

**Issue by stibala** [erpc/erpc#91]
Since version 0.0.25 we experienced occasionally empty responses of `eth_protocolVersion` requests.

**Comment by kasrakhosravi** [comment]
gm @stibala. thanks for reporting

what chain/RPC providers are you using today and has there also been a change in RPCs you have configured in eRPC? It could be the case that certain RPC nodes do not support this method and give an empty result.

**Comment by stibala** [comment]
Thanks for quick reply. We use Alchemy as upstream provider and didn't change it recently. We did test versions 0.0.24, 0.0.25 and 0.0.26 without any other change and we could reproduce the issue with the latter ones but not with 0.0.24.

**Comment by aramalipoor** [comment]
Thanks for the info, I'll try to reproduce it with Alchemy. In meantime have you tried with 0.0.27? In that one we removed a library that used to cause some behaviors like this.

**Comment by stibala** [comment]
We could reproduce it even with 0.0.27 now.

**Comment by stibala** [comment]
Hi, after you couldn't reproduce the issue, I tested it with plain docker image and couldn't reproduce it as well. So I now am convinced it cannot be erpc. The issue can be therefore closed. Thanks for support!

**Comment by kasrakhosravi** [comment]
> Hi, after you couldn't reproduce the issue, I tested it with plain docker image and couldn't reproduce it as well. So I now am convinced it cannot be erpc. The issue can be therefore closed. Thanks for support!

please let us know if this (or similar issues) come up in your testing :)
